LPS-46191 We must deploy registry-api before deploying other modules, or else you can get this exception:
[exec] [ivy:retrieve] :: retrieving :: com.liferay#com.liferay.polls.web     [exec] [ivy:retrieve] 	confs: [default]     [exec] [ivy:retrieve] 	1 artifacts copied, 0 already retrieved (753kB/3ms)     [exec] [ivy:retrieve] :: retrieving :: com.liferay#com.liferay.polls.web     [exec] [ivy:retrieve] 	confs: [default]     [exec] [ivy:retrieve] 	0 artifacts copied, 0 already retrieved (0kB/1ms)     [exec]      [copy] Copying 1 file to /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/lib     [exec]      [copy] Copying 3 files to /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/lib     [exec]     [mkdir] Created dir: /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/classes     [exec]      [copy] Copying 5 files to /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/lib     [exec]      [copy] Copying 2 files to /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/classes     [exec]      [copy] Copied 14 empty directories to 13 empty directories under /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/classes     [exec]     [javac] Compiling 9 source files to /Users/brian/dev/projects/github/liferay-portal/modules/apps/polls/polls-web/docroot/WEB-INF/classes     [exec] [baseline-jar] 1 WARNINGS     [exec] [baseline-jar]  Unused Import-Package instructions: [org.apache.struts.config.*, javax.portlet.*, org.apache.struts.action.*]     [exec] [baseline-jar] com.liferay.polls.web (com.liferay.polls.web-1.0.0.jar) 48     [exec]      [move] Moving 1 file to /Users/brian/dev/projects/github/liferay-portal/tools/sdk/dist     [exec]      [java] Loading jar:file:/Users/brian/dev/bundles/master/tomcat-7.0.42/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties     [exec]      [java] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/registry/Registry     [exec]      [java] 	at com.liferay.portal.tools.deploy.PortletDeployer.main(PortletDeployer.java:51)     [exec]      [java] Caused by: java.lang.ClassNotFoundException: com.liferay.registry.Registry     [exec]      [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)     [exec]      [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)     [exec]      [java] 	at java.security.AccessController.doPrivileged(Native Method)     [exec]      [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)     [exec]      [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)     [exec]      [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)     [exec]      [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)     [exec]      [java] 	... 1 more     [exec]      [java] Java Result: 1     [exec]      [echo] Unable to automatically update web.xml in /Users/brian/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.polls.web-1.0.0.jar.     [exec]      [move] Moving 1 file to /Users/brian/dev/projects/github/liferay-portal/tools/sdk/dist     [exec]      [copy] Copying 1 file to /Users/brian/dev/bundles/master/osgi/modules     [exec] [ivy:retrieve] :: retrieving :: com.liferay#com.liferay.social.activities.web